# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-25 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lang', models.CharField(max_length=10)),
                ('Day_time_date', models.CharField(max_length=30)),
                ('Text', models.CharField(max_length=400)),
                ('Fav_count', models.CharField(max_length=10)),
                ('Ret_count', models.CharField(max_length=10)),
            ],
        ),
    ]
