# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-17 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tweets', '0002_tweets_hashtag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweets',
            old_name='Hashtag',
            new_name='tweet_id',
        ),
        migrations.AddField(
            model_name='tweets',
            name='no_followers',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tweets',
            name='toxic',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tweets',
            name='urls',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tweets',
            name='user_name',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
