# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-17 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tweets', '0003_auto_20180117_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweets',
            name='replies',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
